# Generated by Django 5.2.8 on 2026-01-08 04:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_job_notulen_item_job_notulen_target_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200, unique=True)),
                ('spesifikasi', models.TextField(blank=True, null=True)),
                ('jumlah_total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alat/Tool',
                'verbose_name_plural': 'Alat/Tools',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tgl_pinjam', models.DateTimeField(auto_now_add=True)),
                ('tgl_rencana_kembali', models.DateTimeField()),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('selesai', 'Selesai'), ('overdue', 'Overdue')], default='aktif', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peminjaman_dibuat', to=settings.AUTH_USER_MODEL)),
                ('peminjam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peminjaman_alat', to='core.karyawan')),
            ],
            options={
                'verbose_name': 'Peminjaman',
                'verbose_name_plural': 'Peminjaman',
                'ordering': ['-tgl_pinjam'],
            },
        ),
        migrations.CreateModel(
            name='Pengembalian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tgl_kembali', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('dikembalikan_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengembalian_alat', to='core.karyawan')),
                ('peminjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengembalian', to='toolkeeper.peminjaman')),
            ],
            options={
                'verbose_name': 'Pengembalian',
                'verbose_name_plural': 'Pengembalian',
                'ordering': ['-tgl_kembali'],
            },
        ),
        migrations.CreateModel(
            name='DetailPengembalian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty_kembali', models.PositiveIntegerField()),
                ('kondisi_kembali', models.CharField(choices=[('baik', 'Baik'), ('rusak_ringan', 'Rusak Ringan'), ('rusak_berat', 'Rusak Berat'), ('hilang', 'Hilang')], default='baik', max_length=20)),
                ('pengembalian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pengembalian', to='toolkeeper.pengembalian')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_pengembalian', to='toolkeeper.tool')),
            ],
            options={
                'verbose_name': 'Detail Pengembalian',
                'verbose_name_plural': 'Detail Pengembalian',
            },
        ),
        migrations.CreateModel(
            name='DetailPeminjaman',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty_pinjam', models.PositiveIntegerField()),
                ('kondisi_pinjam', models.CharField(choices=[('baik', 'Baik'), ('rusak_ringan', 'Rusak Ringan'), ('rusak_berat', 'Rusak Berat')], default='baik', max_length=20)),
                ('peminjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_peminjaman', to='toolkeeper.peminjaman')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_peminjaman', to='toolkeeper.tool')),
            ],
            options={
                'verbose_name': 'Detail Peminjaman',
                'verbose_name_plural': 'Detail Peminjaman',
                'unique_together': {('peminjaman', 'tool')},
            },
        ),
    ]
