# Generated by Django 5.2.8 on 2025-12-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_karyawan_alter_leaveevent_nama_orang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Jika diaktifkan, user akan melihat halaman maintenance', verbose_name='Aktifkan Maintenance Mode')),
                ('message', models.TextField(default='Aplikasi sedang dalam proses maintenance. Mohon tunggu beberapa saat...', help_text='Pesan yang ditampilkan ke user saat maintenance mode aktif', verbose_name='Pesan Maintenance')),
                ('estimated_time', models.CharField(blank=True, default='Estimasi selesai dalam 15 menit', help_text="Contoh: 'Estimasi selesai dalam 15 menit' atau '10:30 AM'", max_length=100, verbose_name='Estimasi Waktu Selesai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maintenance Mode',
                'verbose_name_plural': 'Maintenance Mode',
            },
        ),
    ]
