# Generated by Django 5.2.8 on 2025-12-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_maintenancemode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveevent',
            name='google_event_id',
            field=models.CharField(blank=True, help_text='Event IDs dari Google Calendar (comma-separated untuk multiple events)', max_length=500, null=True),
        ),
    ]
