# Generated by Django 5.2.8 on 2025-12-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_leaveevent_google_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nomor_telepon',
            field=models.CharField(blank=True, help_text='Nomor telepon untuk integrasi WA Fontte (e.g., 62812XXXXXXXX)', max_length=20, null=True),
        ),
    ]
