# Generated by Django 5.2.8 on 2025-12-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0013_alter_project_shared_is_shared'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['atasan', 'id'], name='core_custom_atasan__6b9a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='core_custom_usernam_8458f1_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['pic', 'tipe_job'], name='core_job_pic_id_a0e7a8_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['project', 'status'], name='core_job_project_22810c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['aset', 'status'], name='core_job_aset_id_339c24_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['manager_project', 'is_shared'], name='core_projec_manager_4612cd_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_shared'], name='core_projec_is_shar_20dca5_idx'),
        ),
    ]
