# Generated by Django 5.2.8 on 2025-12-22 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customuser_core_custom_atasan__6b9a8a_idx_and_more'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='notulen_item',
            field=models.OneToOneField(blank=True, help_text='Notulen item yang membuat job ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to='meetings.notulenitem'),
        ),
        migrations.AddField(
            model_name='job',
            name='notulen_target_date',
            field=models.DateField(blank=True, help_text='Reference target date dari notulen', null=True),
        ),
    ]
