# Generated by Django 5.2.8 on 2026-02-06 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0015_job_notulen_item_job_notulen_target_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bagian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bagian', models.CharField(max_length=100, verbose_name='Nama Bagian')),
                ('deskripsi', models.TextField(blank=True, help_text='Deskripsi fungsi bagian', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kepala_bagian', models.OneToOneField(blank=True, help_text='User yang menjadi kepala bagian ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bagian_dipimpin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bagian',
                'verbose_name_plural': 'Daftar Bagian',
                'ordering': ['departemen', 'nama_bagian'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='bagian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anggota_bagian', to='core.bagian', verbose_name='Bagian'),
        ),
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_departemen', models.CharField(max_length=100, unique=True, verbose_name='Nama Departemen')),
                ('deskripsi', models.TextField(blank=True, help_text='Deskripsi fungsi departemen', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kepala_departemen', models.OneToOneField(blank=True, help_text='User yang menjadi kepala departemen ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departemen_dipimpin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Departemen',
                'verbose_name_plural': 'Daftar Departemen',
                'ordering': ['nama_departemen'],
            },
        ),
        migrations.AddField(
            model_name='bagian',
            name='departemen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_bagian', to='core.departemen', verbose_name='Departemen'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='departemen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anggota_departemen', to='core.departemen', verbose_name='Departemen'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['departemen'], name='core_custom_departe_646dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['bagian'], name='core_custom_bagian__6320fb_idx'),
        ),
        migrations.AddIndex(
            model_name='bagian',
            index=models.Index(fields=['departemen'], name='core_bagian_departe_83ff8f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bagian',
            unique_together={('departemen', 'nama_bagian')},
        ),
    ]
