# Generated by Django 5.2.8 on 2026-02-06 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_departemen_bagian'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartemenFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(choices=[('dashboard', 'Dashboard'), ('project', 'Project Management'), ('job', 'Job Management'), ('preventive_jobs', 'Preventive Jobs'), ('maintenance_report', 'Maintenance Report'), ('inventory', 'Inventory Management'), ('toolkeeper', 'Toolkeeper'), ('meetings', 'Meetings & Notulen'), ('analytics', 'Analytics & Reports'), ('settings', 'Settings')], max_length=50, verbose_name='Fitur/Menu')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departemen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_allowed', to='core.departemen')),
            ],
            options={
                'verbose_name': 'Departemen Feature Permission',
                'verbose_name_plural': 'Daftar Departemen Feature Permission',
                'ordering': ['departemen', 'feature_key'],
                'indexes': [models.Index(fields=['departemen', 'is_enabled'], name='core_depart_departe_24aa4f_idx')],
                'unique_together': {('departemen', 'feature_key')},
            },
        ),
    ]
