# Generated by Django 5.2.8 on 2026-02-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_departemen_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='departemen',
            name='google_calendar_id',
            field=models.CharField(default='ges3ra8851qk05jqlsfgjct3h4@group.calendar.google.com', help_text='Calendar ID dari Google Workspace untuk departemen ini (cth: abc123@group.calendar.google.com)', max_length=255, verbose_name='Google Calendar ID'),
            preserve_default=False,
        ),
    ]
