# Generated by Django 5.2.8 on 2026-02-07 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_departemen_google_calendar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveevent',
            name='departemen',
            field=models.ForeignKey(blank=True, help_text='Departemen yang punya calendar untuk event ini', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_events', to='core.departemen', verbose_name='Departemen'),
        ),
    ]
