# Generated by Django 5.2.8 on 2026-02-21 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_leaveevent_departemen'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOverdueJobPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_daily_jobs', models.BooleanField(default=True, help_text='Cek untuk menampilkan daily jobs dalam overdue notifications', verbose_name='Tampilkan Daily Jobs')),
                ('show_project_jobs', models.BooleanField(default=True, help_text='Cek untuk menampilkan project jobs dalam overdue notifications', verbose_name='Tampilkan Project Jobs')),
                ('show_preventive_jobs', models.BooleanField(default=True, help_text='Cek untuk menampilkan preventive jobs dalam overdue notifications', verbose_name='Tampilkan Preventive Jobs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overdue_job_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Overdue Job Preference',
                'verbose_name_plural': 'User Overdue Job Preferences',
            },
        ),
    ]
