# Generated by Django 5.2.8 on 2026-02-27 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_useroverduejobpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonnteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(default='https://api.fontte.com/send', help_text='Fontte API endpoint untuk send WA message', max_length=500)),
                ('api_key', models.CharField(help_text='API Key dari Fontte untuk authentikasi', max_length=255, verbose_name='API Key')),
                ('api_secret', models.CharField(help_text='API Secret dari Fontte untuk authentikasi', max_length=255, verbose_name='API Secret')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable WA reminders untuk departemen ini')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fontte_settings_created', to=settings.AUTH_USER_MODEL)),
                ('departemen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fontte_settings', to='core.departemen', verbose_name='Departemen')),
            ],
            options={
                'verbose_name': 'Fontte Settings',
                'verbose_name_plural': 'Fontte Settings',
                'permissions': [('can_manage_fontte', 'Can manage Fontte API settings')],
            },
        ),
    ]
