# Generated by Django 5.2.8 on 2026-02-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_fonttesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fonntesettings',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='fonntesettings',
            name='api_secret',
        ),
        migrations.RemoveField(
            model_name='fonntesettings',
            name='api_url',
        ),
        migrations.AddField(
            model_name='fonntesettings',
            name='country_code',
            field=models.CharField(default='62', help_text='Country code untuk nomor HP (default: 62 untuk Indonesia)', max_length=5),
        ),
        migrations.AddField(
            model_name='fonntesettings',
            name='token',
            field=models.CharField(default='not-configured', help_text='Token dari Fontte dashboard (digunakan di Authorization header)', max_length=255, verbose_name='API Token'),
            preserve_default=False,
        ),
    ]
