# Generated by Django 5.2.8 on 2026-02-27 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_fonttesettings_api_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fonntesettings',
            options={'permissions': [('can_manage_fonte', 'Can manage Fonnte API settings')], 'verbose_name': 'Fonnte Settings', 'verbose_name_plural': 'Fonnte Settings'},
        ),
        migrations.AlterField(
            model_name='fonntesettings',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fonnte_settings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='fonntesettings',
            table='core_fonntesettings',
        ),
    ]
