# Generated by Django 5.2.8 on 2026-04-01 09:42

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_fonntesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='aset',
            field=models.ForeignKey(help_text='Pilih Sub Mesin (level terendah) - Untuk Teknik', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.asetmesin'),
        ),
        migrations.AlterField(
            model_name='job',
            name='fokus',
            field=models.CharField(blank=True, choices=[('Perawatan', 'Perawatan'), ('Perbaikan', 'Perbaikan'), ('Proyek', 'Proyek'), ('Lainnya', 'Lainnya')], default='Perawatan', help_text='Fokus pekerjaan (akan dimigrate ke FokusPekerjaan nanti)', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AsetDepartemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('departemen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aset_departemen_set', to='core.departemen')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.asetdepartemen')),
            ],
            options={
                'verbose_name': 'Aset Departemen',
                'verbose_name_plural': 'Daftar Aset Departemen',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='aset_departemen',
            field=models.ForeignKey(blank=True, help_text='Aset departemen (generic untuk semua departemen non-Teknik)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.asetdepartemen'),
        ),
        migrations.CreateModel(
            name='FokusPekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('urutan', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departemen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fokus_pekerjaan_set', to='core.departemen')),
            ],
            options={
                'verbose_name': 'Fokus Pekerjaan',
                'verbose_name_plural': 'Daftar Fokus Pekerjaan',
                'ordering': ['departemen', 'urutan', 'nama'],
            },
        ),
        migrations.AddIndex(
            model_name='asetdepartemen',
            index=models.Index(fields=['departemen'], name='core_asetde_departe_249ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='asetdepartemen',
            index=models.Index(fields=['tree_id', 'lft'], name='core_asetdepartemen_tree_i730a'),
        ),
        migrations.AddIndex(
            model_name='fokuspekerjaan',
            index=models.Index(fields=['departemen', 'is_active'], name='core_fokusp_departe_732d42_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fokuspekerjaan',
            unique_together={('departemen', 'nama')},
        ),
    ]
