# Generated by Django 5.2.8 on 2026-04-01 09:43

from django.db import migrations


def populate_fokus_pekerjaan(apps, schema_editor):
    """Auto-populate FokusPekerjaan for Teknik dan Operasional departments"""
    Departemen = apps.get_model('core', 'Departemen')
    FokusPekerjaan = apps.get_model('core', 'FokusPekerjaan')
    
    # Fokus untuk Teknik
    teknik_fokus = [
        ('Perawatan', 1),
        ('Perbaikan', 2),
        ('Proyek', 3),
        ('Lainnya', 4),
    ]
    
    # Fokus untuk Operasional
    operasional_fokus = [
        ('Planning', 1),
        ('Koordinasi', 2),
        ('Monitoring', 3),
        ('Laporan', 4),
        ('Evaluasi', 5),
    ]
    
    try:
        # Get Teknik departemen (field name is nama_departemen)
        teknik = Departemen.objects.get(nama_departemen='Teknik')
        for nama, urutan in teknik_fokus:
            FokusPekerjaan.objects.get_or_create(
                nama=nama,
                departemen=teknik,
                defaults={'urutan': urutan, 'is_active': True}
            )
    except Departemen.DoesNotExist:
        pass
    
    try:
        # Get Operasional departemen (field name is nama_departemen)
        operasional = Departemen.objects.get(nama_departemen='Operasional')
        for nama, urutan in operasional_fokus:
            FokusPekerjaan.objects.get_or_create(
                nama=nama,
                departemen=operasional,
                defaults={'urutan': urutan, 'is_active': True}
            )
    except Departemen.DoesNotExist:
        pass


def reverse_populate(apps, schema_editor):
    """Reverse the population - delete created FokusPekerjaan records"""
    FokusPekerjaan = apps.get_model('core', 'FokusPekerjaan')
    FokusPekerjaan.objects.filter(
        nama__in=['Perawatan', 'Perbaikan', 'Proyek', 'Lainnya', 
                   'Planning', 'Koordinasi', 'Monitoring', 'Laporan', 'Evaluasi']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_job_aset_alter_job_fokus_asetdepartemen_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_fokus_pekerjaan, reverse_populate),
    ]
