# Generated by Django 5.2.8 on 2026-04-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_enable_project_feature_for_all_departemen'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAPISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonnte_api_token', models.CharField(blank=True, help_text='Token dari Fonnte untuk WhatsApp API', max_length=500, null=True, verbose_name='Fonnte API Token')),
                ('reminder_send_time', models.TimeField(default='08:00', help_text='Jam berapa reminder meeting dikirim (format HH:MM, timezone Asia/Jakarta)', verbose_name='Waktu Kirim Reminder')),
                ('google_credentials_path', models.CharField(blank=True, help_text='Path relatif ke file JSON credentials (misal: JSON GCP/credentials.json)', max_length=255, null=True, verbose_name='Path ke Google Credentials JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google API Settings',
                'verbose_name_plural': 'Google API Settings',
            },
        ),
        migrations.AddField(
            model_name='departemen',
            name='google_sheet_id',
            field=models.CharField(blank=True, help_text='ID spreadsheet untuk meeting reminder auto-sync (copy dari URL: docs.google.com/spreadsheets/d/{ID}/edit)', max_length=255, null=True, verbose_name='Google Spreadsheet ID (Meeting Reminder)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='fokus',
            field=models.CharField(blank=True, default='', help_text='Fokus pekerjaan (diisi dari FokusPekerjaan model)', max_length=100, null=True),
        ),
    ]
