# Generated by Django 5.2.8 on 2026-05-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_googleapisettings_departemen_google_sheet_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='asetdepartemen',
            name='core_asetdepartemen_tree_i730a',
        ),
    ]
