# Generated by Django 5.2.8 on 2025-11-27 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_karyawan_alter_leaveevent_nama_orang_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventiveJobExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(help_text='Tanggal yang dijadwalkan untuk pekerjaan ini', verbose_name='Tanggal Terjadwal')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled (Terjadwal)'), ('Done', 'Done (Selesai)'), ('Skipped', 'Skipped (Dilewati)'), ('N/A', 'N/A (Tidak Berlaku)')], default='Scheduled', max_length=20, verbose_name='Status')),
                ('actual_date', models.DateField(blank=True, help_text='Tanggal ketika job sebenarnya dilaksanakan', null=True, verbose_name='Tanggal Pelaksanaan Aktual')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan/Findings')),
                ('compliance_type', models.CharField(choices=[('A', 'A - Selesai sesuai jadwal'), ('B', 'B - Selesai terlambat'), ('C', 'C - Selesai dengan bukti/foto'), ('None', 'None - Belum ditentukan')], default='None', help_text='Kategori compliance: A (tepat waktu), B (terlambat), C (dengan bukti)', max_length=10, verbose_name='Tipe Compliance')),
                ('has_attachment', models.BooleanField(default=False, verbose_name='Ada Lampiran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventive_job_executions', to='core.asetmesin', verbose_name='Mesin/Aset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventive_job_executions_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Ditugaskan ke')),
            ],
            options={
                'verbose_name': 'Preventive Job Execution',
                'verbose_name_plural': 'Daftar Preventive Job Executions',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='PreventiveJobAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='preventive_jobs/attachments/%Y/%m/%d/', verbose_name='File')),
                ('deskripsi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Deskripsi')),
                ('tipe_file', models.CharField(choices=[('Image', 'Gambar'), ('Document', 'Dokumen'), ('Video', 'Video'), ('Other', 'Lainnya')], default='Image', max_length=20, verbose_name='Tipe File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventive_job_attachments_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Diunggah oleh')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='preventive_jobs.preventivejobexecution', verbose_name='Execution')),
            ],
            options={
                'verbose_name': 'Preventive Job Attachment',
                'verbose_name_plural': 'Daftar Preventive Job Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PreventiveJobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pekerjaan', models.CharField(help_text='Contoh: Cek Oil Level, Ganti Filter, dll', max_length=255, verbose_name='Nama Pekerjaan')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('periode', models.CharField(choices=[('Harian', 'Harian (Setiap hari)'), ('Mingguan', 'Mingguan (Setiap minggu)'), ('Bulanan', 'Bulanan (Setiap bulan)'), ('Triwulan', 'Triwulan (Setiap 3 bulan)'), ('Tahunan', 'Tahunan (Setiap tahun)'), ('Custom', 'Custom (Interval custom)')], default='Mingguan', max_length=20, verbose_name='Periode Pengulangan')),
                ('interval', models.IntegerField(default=1, help_text='Contoh: 7 (untuk mingguan), 30 (untuk bulanan)', verbose_name='Interval (hari/minggu/bulan/tahun)')),
                ('tanggal_mulai', models.DateField(help_text='Kapan template ini mulai aktif', verbose_name='Tanggal Mulai')),
                ('tanggal_berakhir', models.DateField(blank=True, help_text='Kosongkan jika pengulangan tidak terbatas (ongoing)', null=True, verbose_name='Tanggal Berakhir (Opsional)')),
                ('fokus', models.CharField(choices=[('Perawatan', 'Perawatan'), ('Perbaikan', 'Perbaikan'), ('Inspeksi', 'Inspeksi'), ('Kalibrasi', 'Kalibrasi'), ('Cleaning', 'Cleaning'), ('Lainnya', 'Lainnya')], default='Perawatan', max_length=50, verbose_name='Fokus Pekerjaan')),
                ('prioritas', models.CharField(choices=[('P1', 'P1 - Mendesak'), ('P2', 'P2 - Tinggi'), ('P3', 'P3 - Normal'), ('P4', 'P4 - Rendah')], default='P3', max_length=10, verbose_name='Prioritas')),
                ('notify_24h_before', models.BooleanField(default=True, verbose_name='Notifikasi 24 jam sebelumnya')),
                ('notify_2h_before', models.BooleanField(default=True, verbose_name='Notifikasi 2 jam sebelumnya')),
                ('notify_on_schedule', models.BooleanField(default=False, verbose_name='Notifikasi saat jadwal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aset_mesin', models.ManyToManyField(help_text='Pilih satu atau lebih mesin/aset', related_name='preventive_job_templates', to='core.asetmesin')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventive_job_templates_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat oleh')),
                ('pic', models.ForeignKey(help_text='User yang bertanggung jawab template ini', on_delete=django.db.models.deletion.PROTECT, related_name='preventive_job_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='PIC (Penanggung Jawab)')),
            ],
            options={
                'verbose_name': 'Preventive Job Template',
                'verbose_name_plural': 'Daftar Preventive Job Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='preventivejobexecution',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='preventive_jobs.preventivejobtemplate', verbose_name='Template'),
        ),
        migrations.CreateModel(
            name='PreventiveJobNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('24h_before', 'Notifikasi 24 jam sebelum'), ('2h_before', 'Notifikasi 2 jam sebelum'), ('on_schedule', 'Notifikasi saat jadwal'), ('overdue', 'Notifikasi job overdue'), ('completed', 'Notifikasi job selesai')], default='24h_before', max_length=20, verbose_name='Tipe Notifikasi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Sudah dibaca')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu dibaca')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='preventive_jobs.preventivejobexecution', verbose_name='Execution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventive_job_notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Preventive Job Notification',
                'verbose_name_plural': 'Daftar Preventive Job Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='preventive__user_id_1ed989_idx'), models.Index(fields=['execution'], name='preventive__executi_ab3f57_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='preventivejobtemplate',
            index=models.Index(fields=['is_active', 'tanggal_mulai'], name='preventive__is_acti_4ae142_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivejobtemplate',
            index=models.Index(fields=['pic'], name='preventive__pic_id_f82fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivejobexecution',
            index=models.Index(fields=['status', 'scheduled_date'], name='preventive__status_7e0cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivejobexecution',
            index=models.Index(fields=['assigned_to'], name='preventive__assigne_bd11e2_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivejobexecution',
            index=models.Index(fields=['template'], name='preventive__templat_2c895c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='preventivejobexecution',
            unique_together={('template', 'aset', 'scheduled_date')},
        ),
    ]
