# Generated by Django 5.2.8 on 2025-11-28 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive_jobs', '0004_simplify_interval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: Checklist Perawatan Motor 3 Fasa', max_length=255, verbose_name='Nama Checklist')),
                ('nomor', models.CharField(editable=False, help_text='Auto-generate: CHKL-YYYY-XXX', max_length=50, unique=True, verbose_name='Nomor Checklist')),
                ('kategori', models.CharField(choices=[('Mekanik', 'Mekanik'), ('Elektrik', 'Elektrik'), ('Utility', 'Utility')], max_length=20, verbose_name='Kategori')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('file_template', models.FileField(blank=True, help_text='File referensi checklist untuk download', null=True, upload_to='checklist_templates/', verbose_name='File Template (Excel/PDF)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checklist Template',
                'verbose_name_plural': 'Daftar Checklist Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasil_pengukuran', models.JSONField(blank=True, default=dict, verbose_name='Hasil Pengukuran')),
                ('status_overall', models.CharField(choices=[('OK', 'OK - Semua Normal'), ('NG', 'NG - Ada yang Abnormal'), ('Partial', 'Partial - Sebagian Selesai')], default='Partial', max_length=20, verbose_name='Status Overall')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='checklist_results/', verbose_name='File Checklist (PDF/Excel)')),
                ('tanggal_pengisian', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Pengisian')),
                ('catatan_umum', models.TextField(blank=True, null=True, verbose_name='Catatan Umum')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diisi_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_checklists', to=settings.AUTH_USER_MODEL)),
                ('execution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_result', to='preventive_jobs.preventivejobexecution')),
                ('checklist_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='preventive_jobs.checklisttemplate')),
            ],
            options={
                'verbose_name': 'Checklist Result',
                'verbose_name_plural': 'Daftar Checklist Results',
                'ordering': ['-tanggal_pengisian'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut', models.IntegerField(help_text='Urutan item dalam checklist', verbose_name='No Urut')),
                ('item_pemeriksaan', models.CharField(help_text='Contoh: Tegangan antar fasa', max_length=255, verbose_name='Item Pemeriksaan')),
                ('standar_normal', models.CharField(help_text='Contoh: 380±10% V, Sesuai nameplate, >100 MΩ', max_length=255, verbose_name='Standar/Normal')),
                ('unit', models.CharField(blank=True, help_text='Contoh: V, A, %, MΩ, Hz, mm, dll', max_length=50, null=True, verbose_name='Unit')),
                ('nilai_min', models.FloatField(blank=True, help_text='Untuk validasi range hasil pengukuran', null=True, verbose_name='Nilai Min')),
                ('nilai_max', models.FloatField(blank=True, help_text='Untuk validasi range hasil pengukuran', null=True, verbose_name='Nilai Max')),
                ('tindakan_remark', models.CharField(blank=True, help_text='Kolom catatan atau tindakan jika nilai diluar normal', max_length=255, null=True, verbose_name='Tindakan/Remark')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='preventive_jobs.checklisttemplate')),
            ],
            options={
                'verbose_name': 'Checklist Item',
                'verbose_name_plural': 'Daftar Checklist Items',
                'ordering': ['checklist_template', 'no_urut'],
            },
        ),
        migrations.AddField(
            model_name='preventivejobtemplate',
            name='checklist_template',
            field=models.ForeignKey(blank=True, help_text='Pilih checklist yang harus diisi saat job ditutup (opsional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventive_job_templates', to='preventive_jobs.checklisttemplate', verbose_name='Checklist Template'),
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['kategori', 'is_active'], name='preventive__kategor_93e62c_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistresult',
            index=models.Index(fields=['execution'], name='preventive__executi_2e36fa_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistresult',
            index=models.Index(fields=['checklist_template'], name='preventive__checkli_1ef536_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['checklist_template'], name='preventive__checkli_68356a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistitem',
            unique_together={('checklist_template', 'no_urut')},
        ),
    ]
