# Generated by Django 5.2.8 on 2025-11-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive_jobs', '0011_add_item_type_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresult',
            name='catatan',
            field=models.TextField(blank=True, help_text='Catatan hasil checklist', null=True, verbose_name='Catatan'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='status_item',
            field=models.JSONField(blank=True, default=dict, help_text='Mapping item_id ke status OK/NG', verbose_name='Status Item'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='item_pemeriksaan',
            field=models.CharField(help_text='Contoh: Tegangan antar fasa, Getaran, Suara abnormal, Warna cairan', max_length=255, verbose_name='Item Pemeriksaan'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='item_type',
            field=models.CharField(choices=[('numeric', 'Numeric (dengan Angka)'), ('text', 'Text/Qualitative (Observasi)')], default='numeric', help_text='Numeric: untuk pengukuran angka | Text: untuk observasi visual/audio', max_length=20, verbose_name='Tipe Item'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='nilai_max',
            field=models.FloatField(blank=True, help_text='Untuk validasi range hasil pengukuran (numeric items saja)', null=True, verbose_name='Nilai Max'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='nilai_min',
            field=models.FloatField(blank=True, help_text='Untuk validasi range hasil pengukuran (numeric items saja)', null=True, verbose_name='Nilai Min'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='standar_normal',
            field=models.CharField(help_text='Contoh: 380±10% V, Halus, Bunyi normal, Jernih', max_length=255, verbose_name='Standar/Normal'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='text_options',
            field=models.CharField(blank=True, help_text='Untuk text items, pisahkan dengan semicolon (;). Contoh: Normal;Kasar;Bising;Bergerak', max_length=500, null=True, verbose_name='Pilihan Text'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='unit',
            field=models.CharField(blank=True, help_text='Contoh: V, A, %, MΩ, Hz, mm, dll. Kosongkan untuk item text', max_length=50, null=True, verbose_name='Unit'),
        ),
    ]
