# Generated by Django 5.2.8 on 2025-12-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive_jobs', '0012_checklistresult_catatan_checklistresult_status_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivejobtemplate',
            name='custom_dates',
            field=models.JSONField(blank=True, default=list, help_text='List tanggal dalam sebulan: [2, 7, 14, 28] untuk tgl 2, 7, 14, 28 setiap bulan', verbose_name='Custom Dates'),
        ),
        migrations.AddField(
            model_name='preventivejobtemplate',
            name='schedule_type',
            field=models.CharField(choices=[('interval', 'Interval-Based (Setiap N hari)'), ('custom', 'Custom Dates (Tanggal tertentu setiap bulan)')], default='interval', help_text='Pilih interval regular atau custom dates', max_length=20, verbose_name='Tipe Jadwal'),
        ),
    ]
