# Generated by Django 5.2.8 on 2025-12-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive_jobs', '0013_add_custom_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='item_type',
            field=models.CharField(choices=[('numeric', 'Numeric (dengan Angka)'), ('text', 'Text/Qualitative (Dropdown Pilihan)'), ('free_text', 'Free Text (Input Bebas)')], default='numeric', help_text='Numeric: untuk pengukuran angka | Text: untuk observasi visual/audio', max_length=20, verbose_name='Tipe Item'),
        ),
    ]
