# Generated by Django 5.2.8 on 2025-12-02 05:39

from django.db import migrations


def set_default_item_types(apps, schema_editor):
    """
    Set default item_type for existing ChecklistItem records.
    Logic:
    - If nilai_min or nilai_max is set: type = 'numeric'
    - Else if text_options is set: type = 'text'
    - Else: type = 'free_text' (safest default)
    """
    ChecklistItem = apps.get_model('preventive_jobs', 'ChecklistItem')
    
    for item in ChecklistItem.objects.all():
        if not item.item_type or item.item_type == '':
            # Determine type based on field values
            if item.nilai_min is not None or item.nilai_max is not None:
                item.item_type = 'numeric'
            elif item.text_options:
                item.item_type = 'text'
            else:
                item.item_type = 'free_text'
            
            item.save()


def reverse_default_item_types(apps, schema_editor):
    """
    Reverse operation - set back to empty string
    """
    ChecklistItem = apps.get_model('preventive_jobs', 'ChecklistItem')
    for item in ChecklistItem.objects.all():
        item.item_type = ''
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('preventive_jobs', '0014_alter_checklistitem_item_type'),
    ]

    operations = [
        migrations.RunPython(set_default_item_types, reverse_default_item_types),
    ]
