# Generated by Django 5.2.8 on 2025-12-03 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive_jobs', '0015_set_default_item_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20, verbose_name='Status Sebelumnya')),
                ('to_status', models.CharField(max_length=20, verbose_name='Status Sesudahnya')),
                ('reason', models.CharField(blank=True, help_text="e.g., 'Salah klik', 'Testing', 'Data fix', 'User request'", max_length=255, null=True, verbose_name='Alasan Perubahan')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Perubahan')),
                ('snapshot_data', models.JSONField(blank=True, default=dict, help_text='Simpan state execution saat status berubah', verbose_name='Snapshot Data')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Diubah oleh')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='preventive_jobs.preventivejobexecution', verbose_name='Execution')),
            ],
            options={
                'verbose_name': 'Execution Status Log',
                'verbose_name_plural': 'Daftar Execution Status Logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['execution', '-changed_at'], name='preventive__executi_abe656_idx'), models.Index(fields=['changed_by'], name='preventive__changed_82ae61_idx')],
            },
        ),
    ]
