# Generated by Django 5.2.8 on 2025-12-05 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive_jobs', '0016_executionstatuslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivejobexecution',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Dihapus'),
        ),
        migrations.AddField(
            model_name='preventivejobexecution',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_preventive_job_executions', to=settings.AUTH_USER_MODEL, verbose_name='Dihapus oleh'),
        ),
        migrations.AddField(
            model_name='preventivejobexecution',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Jika True berarti execution dihapus beserta template-nya', verbose_name='Terhapus (Soft)'),
        ),
        migrations.AddField(
            model_name='preventivejobtemplate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Dihapus'),
        ),
        migrations.AddField(
            model_name='preventivejobtemplate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_preventive_job_templates', to=settings.AUTH_USER_MODEL, verbose_name='Dihapus oleh'),
        ),
        migrations.AddField(
            model_name='preventivejobtemplate',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Jika True berarti template dihapus dan berada di recycle bin', verbose_name='Terhapus (Soft)'),
        ),
    ]
