# Generated by Django 5.2.8 on 2025-12-11 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive_jobs', '0017_add_soft_delete_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistShareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penerima_nama', models.CharField(max_length=255, verbose_name='Nama Penerima')),
                ('penerima_wa', models.CharField(max_length=20, verbose_name='Nomor WA Penerima')),
                ('share_link', models.URLField(verbose_name='Share Link')),
                ('share_token', models.CharField(max_length=255, verbose_name='Share Token')),
                ('status_pengiriman', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status Pengiriman WA')),
                ('pesan_wa', models.TextField(blank=True, null=True, verbose_name='Pesan WA yang Dikirim')),
                ('dikirim_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Dikirim')),
                ('accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Link Diakses')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Checklist Disubmit')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Pesan Error (jika ada)')),
            ],
            options={
                'verbose_name': 'Checklist Share Log',
                'verbose_name_plural': 'Daftar Checklist Share Logs',
                'ordering': ['-dikirim_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Kontak')),
                ('nomor_wa', models.CharField(help_text='Format: 628xx (dengan kode negara)', max_length=20, unique=True, verbose_name='Nomor WhatsApp')),
                ('tipe_kontak', models.CharField(choices=[('Personal', 'Personal (User PIC)'), ('Team', 'Team (Personil Team)'), ('External', 'External (Kontraktor/Vendor)')], default='Personal', max_length=20, verbose_name='Tipe Kontak')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Contact',
                'verbose_name_plural': 'Daftar WhatsApp Contacts',
                'ordering': ['nama'],
            },
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='accessed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Akses Share Link'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='accessed_by_name',
            field=models.CharField(blank=True, help_text='Nama orang yang mengakses link share', max_length=255, null=True, verbose_name='Nama Orang yang Akses'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='is_submitted_via_share',
            field=models.BooleanField(default=False, help_text='True jika checklist diisi melalui share link WA', verbose_name='Submit via Share Link'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='share_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Share Link Dibuat'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='share_token',
            field=models.CharField(blank=True, help_text='Unique token untuk share link ke WA', max_length=255, null=True, unique=True, verbose_name='Share Token'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Submit Checklist via Share Link'),
        ),
        migrations.AddIndex(
            model_name='checklistresult',
            index=models.Index(fields=['share_token'], name='preventive__share_t_f68f4a_idx'),
        ),
        migrations.AddField(
            model_name='checklistsharelog',
            name='checklist_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_logs', to='preventive_jobs.checklistresult', verbose_name='Checklist Result'),
        ),
        migrations.AddField(
            model_name='checklistsharelog',
            name='dikirim_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_shares_sent', to=settings.AUTH_USER_MODEL, verbose_name='Dikirim oleh'),
        ),
        migrations.AddField(
            model_name='checklistsharelog',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_share_logs', to='preventive_jobs.preventivejobexecution', verbose_name='Execution'),
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User yang punya nomor ini (opsional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_contacts', to=settings.AUTH_USER_MODEL, verbose_name='User Terkait'),
        ),
        migrations.AddIndex(
            model_name='checklistsharelog',
            index=models.Index(fields=['execution'], name='preventive__executi_7f40fb_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistsharelog',
            index=models.Index(fields=['share_token'], name='preventive__share_t_0dd0d8_idx'),
        ),
    ]
