# Generated by Django 5.2.8 on 2025-12-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive_jobs', '0018_checklistsharelog_whatsappcontact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistresult',
            name='status_overall',
            field=models.CharField(choices=[('Pending', 'Pending - Share Link Dibuat (Belum Dibuka)'), ('Partial', 'Partial - Sebagian Selesai'), ('OK', 'OK - Semua Normal'), ('NG', 'NG - Ada yang Abnormal')], default='Pending', max_length=20, verbose_name='Status Overall'),
        ),
    ]
