# Generated by Django 5.2.8 on 2025-12-22 03:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0014_customuser_core_custom_atasan__6b9a8a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('no_dokumen_base', models.CharField(default='F.93/WM/01/03', help_text='Format: F.93/WM/01/03 (tetap, dikonfigurasi di settings)', max_length=50)),
                ('no_urut', models.IntegerField(help_text='Nomor urut otomatis per base (0001, 0002, dst)')),
                ('no_dokumen', models.CharField(editable=False, help_text='Auto-generated: F.93/WM/01/03/0001', max_length=100, unique=True)),
                ('revisi', models.IntegerField(default=0)),
                ('terbitan', models.IntegerField(default=1)),
                ('tanggal_dokumen', models.DateField(auto_now_add=True)),
                ('tanggal_meeting', models.DateField()),
                ('hari', models.CharField(editable=False, max_length=20)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('tempat', models.CharField(max_length=255)),
                ('agenda', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('qr_code_token', models.CharField(editable=False, help_text='Unique token untuk QR code', max_length=100, unique=True)),
                ('qr_code_active', models.BooleanField(default=False, help_text='QR code aktif/inactive')),
                ('qr_code_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting/Notulen Rapat',
                'verbose_name_plural': 'Daftar Meeting/Notulen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingPeserta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('nik', models.CharField(blank=True, max_length=20, null=True)),
                ('bagian', models.CharField(blank=True, max_length=255, null=True)),
                ('status_kehadiran', models.CharField(choices=[('hadir', 'Hadir'), ('izin', 'Izin'), ('alpa', 'Alpa')], default='hadir', max_length=20)),
                ('tipe_peserta', models.CharField(choices=[('internal', 'Internal User'), ('external', 'External Peserta')], editable=False, max_length=20)),
                ('waktu_check_in', models.DateTimeField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
                ('peserta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_peserta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Peserta',
                'verbose_name_plural': 'Daftar Meeting Peserta',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='peserta',
            field=models.ManyToManyField(blank=True, related_name='meetings', through='meetings.MeetingPeserta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotulenItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('no', models.IntegerField(help_text='Nomor urut dalam 1 meeting')),
                ('pokok_bahasan', models.TextField(help_text='Hasil diskusi/keputusan')),
                ('tanggapan', models.TextField(blank=True, help_text='Detail/penjelasan', null=True)),
                ('target_deadline', models.DateField(help_text='Target deadline dari diskusi (soft deadline)')),
                ('status', models.CharField(choices=[('open', 'Open'), ('progress', 'Progress'), ('done', 'Done'), ('overdue', 'Overdue')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('job_created', models.ForeignKey(blank=True, help_text='Job yang dibuat dari notulen item ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notulen_items', to='core.job')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notulen_items', to='meetings.meeting')),
                ('pic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notulen_items_assigned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notulen Item',
                'verbose_name_plural': 'Daftar Notulen Item',
                'ordering': ['meeting', 'no'],
            },
        ),
        migrations.AddIndex(
            model_name='meetingpeserta',
            index=models.Index(fields=['meeting', 'tipe_peserta'], name='meetings_me_meeting_e07e62_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingpeserta',
            index=models.Index(fields=['nik'], name='meetings_me_nik_43817f_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingpeserta',
            constraint=models.UniqueConstraint(condition=models.Q(('peserta__isnull', False)), fields=('meeting', 'peserta'), name='unique_internal_peserta'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['tanggal_meeting'], name='meetings_me_tanggal_9d5f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status'], name='meetings_me_status_14fbb6_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['qr_code_token'], name='meetings_me_qr_code_214c35_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['no_dokumen_base', 'no_urut'], name='meetings_me_no_doku_d0ed89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together={('no_dokumen_base', 'no_urut')},
        ),
        migrations.AddIndex(
            model_name='notulenitem',
            index=models.Index(fields=['pic', 'status'], name='meetings_no_pic_id_405f92_idx'),
        ),
        migrations.AddIndex(
            model_name='notulenitem',
            index=models.Index(fields=['target_deadline'], name='meetings_no_target__d4b7c1_idx'),
        ),
        migrations.AddIndex(
            model_name='notulenitem',
            index=models.Index(fields=['job_created'], name='meetings_no_job_cre_76f760_idx'),
        ),
        migrations.AddConstraint(
            model_name='notulenitem',
            constraint=models.UniqueConstraint(fields=('meeting', 'no'), name='unique_notulen_item_per_meeting'),
        ),
    ]
