# Generated by Django 5.2.8 on 2025-12-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingpeserta',
            name='status_kehadiran',
            field=models.CharField(choices=[('belum', 'Belum Diisi'), ('hadir', 'Hadir'), ('izin', 'Izin'), ('alpa', 'Alpa')], default='belum', max_length=20),
        ),
    ]
