# Generated by Django 5.2.8 on 2025-12-24 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_meetingpeserta_status_kehadiran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notulenitem',
            name='pic_eksternal',
            field=models.CharField(blank=True, help_text='Nama PIC jika bukan dari sistem', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notulenitem',
            name='pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notulen_items_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
