# Generated by Django 5.2.8 on 2026-02-27 04:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_notulenitem_pic_eksternal_alter_notulenitem_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timing_type', models.CharField(choices=[('1day_08am', '1 Hari Sebelum Pukul 08:00'), ('10min_before', '10 Menit Sebelum')], help_text='Tipe reminder: 1 hari sebelum 8am atau 10 menit sebelum', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scheduled_time', models.DateTimeField(help_text='Waktu ketika reminder dijadwalkan dikirim')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Waktu reminder benar-benar dikirim', null=True)),
                ('message_id', models.CharField(blank=True, help_text='Message ID dari Fontte API', max_length=255, null=True)),
                ('error_log', models.TextField(blank=True, help_text='Error detail jika gagal', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='meetings.meeting')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='meetings.meetingpeserta')),
            ],
            options={
                'verbose_name': 'Meeting Reminder',
                'verbose_name_plural': 'Daftar Meeting Reminder',
                'ordering': ['scheduled_time'],
                'indexes': [models.Index(fields=['meeting', 'status'], name='meetings_me_meeting_5b8a6d_idx'), models.Index(fields=['scheduled_time'], name='meetings_me_schedul_4acba5_idx'), models.Index(fields=['status'], name='meetings_me_status_b3950e_idx')],
                'constraints': [models.UniqueConstraint(fields=('meeting', 'peserta', 'timing_type'), name='unique_reminder_per_peserta_timing')],
            },
        ),
    ]
