# Generated by Django 5.2.8 on 2026-01-06 04:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode', models.CharField(help_text='Kode barang/SKU', max_length=50, unique=True)),
                ('nama', models.CharField(help_text='Nama barang', max_length=255)),
                ('spesifikasi', models.TextField(blank=True, help_text='Deskripsi/spesifikasi teknis barang', null=True)),
                ('lokasi_penyimpanan', models.CharField(blank=True, help_text='Lokasi penyimpanan (misal: Rak A1, Bin 3)', max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Barang',
                'verbose_name_plural': 'Daftar Barang',
                'ordering': ['kode'],
                'indexes': [models.Index(fields=['kode'], name='inventory_b_kode_db934e_idx'), models.Index(fields=['status'], name='inventory_b_status_00b0a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=0, help_text='Jumlah stok sekarang', validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_level', to='inventory.barang')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Level',
                'verbose_name_plural': 'Stock Levels',
            },
        ),
    ]
