# Generated by Django 5.2.8 on 2026-01-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='kode',
            field=models.CharField(blank=True, help_text='Kode barang/SKU (auto-generated)', max_length=50, null=True, unique=True),
        ),
    ]
