# Generated by Django 5.2.8 on 2026-01-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_barang_kode'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='kategori',
            field=models.CharField(choices=[('electrical', 'Electrical Components'), ('mechanical', 'Mechanical Components'), ('hydraulic', 'Hydraulic & Pneumatic'), ('seals', 'Seals & Gaskets'), ('fasteners', 'Fasteners & Hardware'), ('lubricants', 'Lubricants & Fluids'), ('consumables', 'Consumables')], default='mechanical', help_text='Kategori barang', max_length=20),
        ),
    ]
