# Generated by Django 5.2.8 on 2026-01-20 03:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_barang_kategori'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='kategori',
            field=models.CharField(choices=[('electrical', 'Electrical Components'), ('mechanical', 'Mechanical Components'), ('hydraulic', 'Hydraulic & Pneumatic'), ('seals', 'Seals & Gaskets'), ('fasteners', 'Fasteners & Hardware'), ('lubricants', 'Lubricants & Fluids'), ('consumables', 'Consumables')], default='mechanical', help_text='Pilih kategori barang sesuai tipenya', max_length=20),
        ),
        migrations.CreateModel(
            name='StockExportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_grup', models.CharField(help_text="Nama grup WA penerima (e.g., 'Warehouse Team', 'Management')", max_length=255)),
                ('nomor_grup_wa', models.CharField(help_text='Nomor grup WhatsApp (format: 628xx untuk personal, bisa juga group ID)', max_length=20)),
                ('jadwal', models.CharField(choices=[('daily', 'Harian (Setiap hari)'), ('weekly', 'Mingguan (Setiap Senin)'), ('monthly', 'Bulanan (Awal bulan)'), ('manual', 'Manual (Dipicu manual saja)')], default='manual', help_text='Jadwal pengiriman otomatis', max_length=20)),
                ('waktu_kirim', models.TimeField(default='09:00', help_text='Jam berapa laporan akan dikirim (format: HH:MM)')),
                ('include_kategori', models.CharField(blank=True, help_text='Kategori yang disertakan (kosongkan untuk semua). Format: electrical,mechanical,hydraulic', max_length=255, null=True)),
                ('pesan_tambahan', models.TextField(blank=True, help_text='Pesan tambahan sebelum daftar stok (opsional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Aktifkan/nonaktifkan pengiriman otomatis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Terakhir dikirim')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_export_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat oleh')),
            ],
            options={
                'verbose_name': 'Stock Export Schedule',
                'verbose_name_plural': 'Stock Export Schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockExportSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False, help_text='Aktifkan untuk mengirim PDF otomatis')),
                ('frequency', models.CharField(choices=[('daily', 'Setiap Hari'), ('weekly', 'Setiap Minggu'), ('monthly', 'Setiap Bulan')], default='daily', help_text='Frekuensi pengiriman', max_length=20)),
                ('send_time', models.TimeField(default='08:00:00', help_text='Jam pengiriman (format HH:MM:SS)')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], default=0, help_text='Hari untuk pengiriman mingguan')),
                ('day_of_month', models.IntegerField(default=1, help_text='Tanggal untuk pengiriman bulanan (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('wa_groups', models.JSONField(blank=True, default=list, help_text="Daftar grup WA untuk menerima PDF (format: [{'group_id': 'xxx', 'group_name': 'Grup 1'}, ...])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_export_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Export Setting',
                'verbose_name_plural': 'Stock Export Settings',
            },
        ),
        migrations.CreateModel(
            name='StockExportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wa_group_id', models.CharField(help_text='ID grup WA yang dituju', max_length=255)),
                ('wa_group_name', models.CharField(help_text='Nama grup WA', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Terkirim'), ('failed', 'Gagal')], default='pending', max_length=20)),
                ('pdf_file', models.CharField(blank=True, help_text='Nama file PDF yang dikirim', max_length=255)),
                ('error_message', models.TextField(blank=True, help_text='Pesan error jika pengiriman gagal')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Waktu pengiriman berhasil', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.stockexportsetting')),
            ],
            options={
                'verbose_name': 'Stock Export Log',
                'verbose_name_plural': 'Stock Export Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
