# Generated by Django 5.2.8 on 2026-01-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_barang_kategori_stockexportschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockexportsetting',
            name='fontte_api_url',
            field=models.URLField(default='https://api.fontte.com/v1', help_text='Base URL untuk Fontte API'),
        ),
        migrations.AddField(
            model_name='stockexportsetting',
            name='fontte_connected',
            field=models.BooleanField(default=False, help_text='Status koneksi ke Fontte'),
        ),
        migrations.AddField(
            model_name='stockexportsetting',
            name='fontte_last_check',
            field=models.DateTimeField(blank=True, help_text='Waktu pengecekan koneksi terakhir', null=True),
        ),
        migrations.AddField(
            model_name='stockexportsetting',
            name='fontte_token',
            field=models.CharField(blank=True, help_text='Token API WA Fontte (opsional, jika kosong menggunakan default dari settings)', max_length=255),
        ),
    ]
