# Generated by Django 5.2.8 on 2026-02-27 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockexportsetting_fontte_api_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockexportschedule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockexportsetting',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='StockExportLog',
        ),
        migrations.DeleteModel(
            name='StockExportSchedule',
        ),
        migrations.DeleteModel(
            name='StockExportSetting',
        ),
    ]
